name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy CLI
        uses: ankurk91/install-trivy-cli-action@v2
        with:
         version: latest # or a specific version like 'v0.64.0'
         cache: true # or set to false, true by default
      - name: Run Trivy scan on a container image
        shell: pwsh
        run: |
          #trivy image --severity CRITICAL <ImageName>
          $template = @"
          {{- if .Results }}
          TRIVY SECURITY REPORT
          =====================

          {{- range .Results }}
          Target: {{ .Target }}
          Type: {{ .Type }}

          {{- if .Vulnerabilities }}
          VULNERABILITIES:
          {{- range .Vulnerabilities }}
          ----------------------------------------
          ID:        {{ .VulnerabilityID }}
          Package:   {{ .PkgName }}
          Installed: {{ .InstalledVersion }}
          Fixed:     {{ .FixedVersion }}
          Severity:  {{ .Severity }}
          Title:     {{ .Title }}
          {{- end }}
          {{- else }}
          No vulnerabilities found.
          {{- end }}

          {{ end }}
          {{- else }}
          No scan results.
          {{- end }}
          "@

          Set-Content -Path "${{ github.workspace }}\trivy-template.tpl" -Value "$template"
          docker pull hello-world
          trivy image --format template --template "@${{ github.workspace }}\trivy-template.tpl" hello-world
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-template
          path: ${{ github.workspace }}\trivy-template.tpl
                


