name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #- name: Build an image from Dockerfile
       # run: docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "fs"
          scan-ref: docker.io/library/hello-world:latest
          format: 'template'
          template: "@${GITHUB_WORKSPACE}/my_template.tpl"
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: ${GITHUB_WORKSPACE}/my_template.tpl
