name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build & Trivy Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build image from YOUR Dockerfile
      - name: Build Docker image
        run: docker build -t trivy-demo:latest .

      # Trivy Image Scan
      - name: Run Trivy image vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: trivy-demo:latest
          format: template
          template: "@/contrib/html.tpl"
          output: trivy-image-report.html
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          exit-code: '0'   # ✅ pipeline will NOT fail

      # Upload report
      - name: Upload Trivy HTML report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-security-report
          path: trivy-image-report.html
